default: &default
  cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SERCRET'] %>

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
